apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app
  namespace: note-taking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
      - name: note-app
        image: note-taking-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: MONGODB_URI
          value: "mongodb://admin:password@mongodb-service:27017/note-taking-app?authSource=admin"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: REDIS_ENABLED
          value: "true"
        - name: JWT_SECRET
          value: "your-super-secret-jwt-key-here-change-in-production"
        - name: JWT_REFRESH_SECRET
          value: "your-super-secret-refresh-key-here-change-in-production"
        - name: JWT_ACCESS_EXPIRY
          value: "15m"
        - name: JWT_REFRESH_EXPIRY
          value: "7d"
        - name: CORS_ORIGIN
          value: "*"
        - name: CORS_CREDENTIALS
          value: "true"
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: note-app-service
  namespace: note-taking-app
  labels:
    app: note-app
spec:
  selector:
    app: note-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
